databases:
  - name: nomina-db
    plan: free

services:
  - type: web
    name: nomina-simple-es
    env: docker
    plan: free
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: nomina-db
          property: connectionString
